# Generated by Django 5.2.14 on 2026-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_phone_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="goods_wage_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="درصد سهم تکنسین از کالا / قطعه (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="service_wage_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="درصد سهم تکنسین از اجرت خدمات (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="travel_wage_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="درصد سهم تکنسین از ایاب و ذهاب (0-100)",
                max_digits=5,
            ),
        ),
    ]
