# Generated by Django 5.2.14 on 2026-05-29 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0006_payment_gateway_settings'),
        ('tenants', '0006_phase26_sms_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSMSMessageTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_available_technician', 'سفارش جدید - تکنسین\u200cها'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر شرکت'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک - مدیر شرکت'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک - مدیر شرکت'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک - مدیر شرکت'), ('subscription_expired_admin', 'پایان اشتراک - مدیر شرکت'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی - مدیر شرکت')], max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('payer', models.CharField(choices=[('COMPANY', 'شرکت'), ('PLATFORM', 'مالک پلتفرم')], default='COMPANY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('default_company_sms_enabled', models.BooleanField(default=True)),
                ('send_start_time', models.TimeField(blank=True, null=True)),
                ('send_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform SMS Message Type Setting',
                'ordering': ['payer', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSMSProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Platform SMS Provider', max_length=100)),
                ('provider_type', models.CharField(choices=[('kavenegar', 'Kavenegar'), ('ghasedak', 'Ghasedak'), ('melipayamak', 'MeliPayamak'), ('fake', 'Fake (Testing)')], default='fake', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('sender_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform SMS Provider Setting',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSMSOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر شرکت'), ('order_available_technician', 'سفارش جدید - تکنسین\u200cها'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'پذیرش سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر شرکت'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری'), ('sms_credit_low_admin', 'کم بودن اعتبار پیامک - مدیر شرکت'), ('sms_credit_empty_admin', 'اتمام اعتبار پیامک - مدیر شرکت'), ('subscription_expiring_admin', 'نزدیک شدن پایان اشتراک - مدیر شرکت'), ('subscription_expired_admin', 'پایان اشتراک - مدیر شرکت'), ('platform_payment_success_admin', 'پرداخت موفق پلتفرمی - مدیر شرکت')], max_length=80)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'در صف ارسال'), ('sending', 'در حال ارسال'), ('sent', 'ارسال شده'), ('delivered', 'ارسال موفق'), ('failed', 'ارسال ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('sending_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_sms_messages', to='tenants.company')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_messages', to='platform_core.platformsmsprovidersetting')),
            ],
            options={
                'verbose_name': 'Platform SMS Outbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'send_at'], name='platform_sms_due_idx'), models.Index(fields=['recipient_company', 'template_key'], name='platform_sms_company_key_idx')],
            },
        ),
    ]
