# Generated by Django 5.2.14 on 2026-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_alter_invoiceitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="technician_goods_wage_percent_snapshot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="technician_service_wage_percent_snapshot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="technician_travel_wage_percent_snapshot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="row_type",
            field=models.CharField(
                choices=[
                    ("service", "اجرت خدمات"),
                    ("goods", "کالا / قطعه"),
                    ("travel", "ایاب و ذهاب"),
                ],
                default="service",
                help_text="نوع ردیف برای محاسبه دستمزد تکنسین.",
                max_length=10,
            ),
        ),
    ]
