# Generated by RastiClean financial policy phase 2.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_backfill_extra_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="settled_discount_code_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="DiscountCode id used at settlement time, stored without FK for audit stability.",
                null=True,
            ),
        ),
    ]
