# Generated by RastiClean Phase 3 public invoice link patch.
from django.db import migrations
import secrets
import string


def make_code(invoice_id, existing):
    alphabet = string.ascii_letters + string.digits
    for _ in range(50):
        token = ''.join(secrets.choice(alphabet) for _ in range(6))
        code = f"{invoice_id}-{token}"
        if code not in existing:
            existing.add(code)
            return code
    raise RuntimeError(f"Could not generate unique public_code for invoice {invoice_id}")


def backfill_public_codes(apps, schema_editor):
    Invoice = apps.get_model('invoices', 'Invoice')
    existing = set(
        Invoice.objects.exclude(public_code__isnull=True)
        .exclude(public_code='')
        .values_list('public_code', flat=True)
    )
    invoices = list(Invoice.objects.filter(public_code__isnull=True).order_by('id'))
    invoices += list(Invoice.objects.filter(public_code='').order_by('id'))
    if not invoices:
        return
    for invoice in invoices:
        invoice.public_code = make_code(invoice.id, existing)
    Invoice.objects.bulk_update(invoices, ['public_code'], batch_size=500)


def noop_reverse(apps, schema_editor):
    # Keep generated public codes on rollback.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('invoices', '0008_invoice_settled_discount_code_id'),
    ]

    operations = [
        migrations.RunPython(backfill_public_codes, noop_reverse),
    ]
