# Generated by Django 5.2.14 on 2026-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_sms_outbox_delivery_states'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprovider',
            options={'ordering': ['company_id', 'name']},
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='send_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled send time. Empty means send as soon as possible.', null=True),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='status',
            field=models.CharField(choices=[('queued', 'در صف ارسال'), ('sending', 'در حال ارسال'), ('sent', 'ارسال شده'), ('delivered', 'ارسال موفق'), ('failed', 'ارسال ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='template_key',
            field=models.CharField(blank=True, choices=[('order_created_admin', 'سفارش جدید - مدیر'), ('order_available_technician', 'سفارش جدید - تکنسین'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'قبول سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='key',
            field=models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر'), ('order_available_technician', 'سفارش جدید - تکنسین'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'قبول سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر'), ('order_cancel_approved_technician', 'تأیید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='send_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='send_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='template_text',
            field=models.TextField(help_text='Django template syntax. Example: {{ order_id }}, {{ customer_name }}'),
        ),
    ]
