# Generated by Django 5.2.14 on 2026-05-31 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0005_clean_sms_outbox_no_legacy"),
        ("tenants", "0006_phase26_sms_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSMasterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Event key matching NotificationSetting / PlatformSMSMessageTypeSetting keys.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("company", "شرکت (پرداخت شرکت)"),
                            ("platform", "پلتفرم (پرداخت مالک)"),
                        ],
                        default="company",
                        max_length=10,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("customer", "مشتری"),
                            ("technician", "نیروی خدماتی"),
                            ("admin", "مدیر شرکت"),
                            ("platform_admin", "مدیر پلتفرم"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "template_text",
                    models.TextField(
                        help_text="Django template syntax. Variables: {{ company_name }}, {{ customer_name }}, etc."
                    ),
                ),
                (
                    "allowed_variables",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of supported variables for this template.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMS Master Template",
                "verbose_name_plural": "SMS Master Templates",
                "ordering": ["scope", "key"],
            },
        ),
        migrations.CreateModel(
            name="SMSTemplateChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(max_length=80)),
                (
                    "current_template_text",
                    models.TextField(
                        blank=True,
                        help_text="Snapshot of the template text at request time.",
                    ),
                ),
                (
                    "requested_template_text",
                    models.TextField(
                        help_text="The new text requested by company admin."
                    ),
                ),
                (
                    "requested_tone",
                    models.CharField(
                        choices=[
                            ("formal", "رسمی"),
                            ("friendly", "دوستانه"),
                            ("short", "کوتاه و عملیاتی"),
                            ("detailed", "مفصل و توضیحی"),
                            ("custom", "سفارشی"),
                        ],
                        default="custom",
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Company admin's reason/note for the change.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_response",
                    models.TextField(
                        blank=True,
                        help_text="Platform owner's response/note on approval or rejection.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_template_change_requests",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_sms_template_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_sms_template_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Template Change Request",
                "verbose_name_plural": "SMS Template Change Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
