# Generated by Django 5.2.14 on 2026-05-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_smsmastertemplate_smstemplatechangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="smstemplatechangerequest",
            name="approved_template_text",
            field=models.TextField(
                blank=True,
                help_text="Final text approved/corrected by platform owner. May differ from requested_template_text.",
            ),
        ),
    ]
