# Generated by Django 5.2.14 on 2026-05-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type_and_more'),
        ('tenants', '0006_phase26_sms_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=100)),
                ('target_app', models.CharField(blank=True, max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('recorded', 'ثبت شده'), ('dispatched', 'پردازش شده'), ('skipped', 'رد شده'), ('failed', 'ناموفق')], db_index=True, default='recorded', max_length=20)),
                ('result_message', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='tenants.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'event_key', 'created_at'], name='notif_event_company_key_idx'), models.Index(fields=['target_app', 'target_model', 'target_id'], name='notif_event_target_idx')],
            },
        ),
    ]
